services:

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: gitlab.local
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"
      - "2222:22"

    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab

    shm_size: "256m"

    networks:
      gitlab-network:
        aliases:
          - gitlab.local

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: unless-stopped

    volumes:
      - ./runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - gitlab-network

networks:
  gitlab-network:
    name: gitlab-network