stages:
  - test
  - build

test:
  stage: test
  image: python:3.12

  before_script:
    - pip install -r requirements.txt

  script:
    - pytest

build:
  stage: build
  image: docker:cli

  variables:
    DOCKER_HOST: "unix:///var/run/docker.sock"

  script:
    - echo "Building application..."
    - docker build -t internal-demo-app .